export enum ShipmentStatus {
  CREATED = 'CREATED',
  PICKUP_CONFIRMED = 'PICKUP_CONFIRMED',
  IN_TRANSIT = 'IN_TRANSIT',
  CUSTOMS_CLEARED = 'CUSTOMS_CLEARED',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  SETTLEMENT_INITIATED = 'SETTLEMENT_INITIATED',
  SETTLEMENT_COMPLETED = 'SETTLEMENT_COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum MilestoneEvent {
  CREATED = 'CREATED',
  PICKUP_CONFIRMED = 'PICKUP_CONFIRMED',
  IN_TRANSIT = 'IN_TRANSIT',
  CUSTOMS_CLEARED = 'CUSTOMS_CLEARED',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  SETTLEMENT_INITIATED = 'SETTLEMENT_INITIATED',
  SETTLEMENT_COMPLETED = 'SETTLEMENT_COMPLETED',
  PROOF_SUBMITTED = 'PROOF_SUBMITTED',
  CANCELLED = 'CANCELLED',
}
